# Generated by Django 3.1.2 on 2020-11-06 20:10

from django.db import migrations, models
import django.db.models.deletion
import supplyr.inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.Category.get_image_upload_path)),
                ('image_sm', models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.Category.get_image_sm_upload_path)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=supplyr.inventory.models.ProductImage.get_image_upload_path)),
                ('image_sm', models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_sm_upload_path)),
                ('image_md', models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_md_upload_path)),
                ('image_lg', models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_md_upload_path)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_temp', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('option1_value', models.CharField(blank=True, max_length=150, null=True)),
                ('option2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('option2_value', models.CharField(blank=True, max_length=150, null=True)),
                ('option3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('option3_value', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_variants', to='inventory.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='inventory.category')),
            ],
        ),
    ]
