# Generated by Django 3.1.12 on 2021-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20211015_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='allow_inventory_tracking',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='allow_overselling',
            field=models.BooleanField(null=True),
        ),
    ]
