# Generated by Django 3.1.4 on 2021-02-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210117_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='sale_price',
            new_name='actual_price',
        ),
    ]
