# Generated by Django 3.0.8 on 2020-08-10 18:05

from django.db import migrations, models
import supplyr.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=supplyr.inventory.models.ProductImage.get_image_upload_path),
        ),
    ]
