# Generated by Django 3.1.12 on 2021-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211109_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='allow_overselling',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
