# Generated by Django 3.1.12 on 2021-11-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211109_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='allow_inventory_tracking',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='allow_overselling',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_inventory_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_overselling',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
