# Generated by Django 3.0.8 on 2020-08-10 20:38

from django.db import migrations, models
import django.db.models.deletion
import supplyr.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200810_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_sm_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.Product'),
        ),
    ]
