# Generated by Django 3.2.4 on 2021-12-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211113_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.Tags'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
