# Generated by Django 3.1.12 on 2022-01-10 15:10

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220108_1505'),
        ('inventory', '0007_auto_20211201_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificBuyerDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', django_mysql.models.EnumField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.buyerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
