# Generated by Django 3.0.8 on 2020-08-12 13:11

from django.db import migrations, models
import supplyr.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200810_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_md',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_md_upload_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_sm_upload_path),
        ),
    ]
