# Generated by Django 3.1.12 on 2021-08-30 22:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210828_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=django_mysql.models.EnumField(blank=True, choices=[('mg', 'Milligram'), ('gm', 'Gram'), ('kg', 'Kilogram'), ('lbs', 'Pound-Mass')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
