# Generated by Django 3.1.12 on 2022-01-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220108_1505'),
        ('inventory', '0008_productspecificbuyerdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificbuyerdiscount',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='productspecificbuyerdiscount',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_products', to='profiles.buyerprofile'),
        ),
    ]
