# Generated by Django 3.0.8 on 2020-08-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20200812_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_variants', to='inventory.ProductImage'),
        ),
    ]
