# Generated by Django 3.1.12 on 2021-08-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210805_1348'),
        ('inventory', '0008_auto_20210825_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='profiles.sellerprofile'),
        ),
    ]
