# Generated by Django 3.1.12 on 2021-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210825_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
