# Generated by Django 3.0.8 on 2020-08-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200820_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='serial',
            new_name='order',
        ),
    ]
