# Generated by Django 3.1.12 on 2022-01-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_buyerdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdiscount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='inventory.buyerdiscount'),
        ),
    ]
