# Generated by Django 3.1.12 on 2021-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_tags_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tags',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
