# Generated by Django 3.1.12 on 2022-01-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20220108_1505'),
        ('inventory', '0011_auto_20220112_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdiscount',
            old_name='discount_value_type',
            new_name='discount_type',
        ),
        migrations.RemoveField(
            model_name='buyerdiscount',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='buyerdiscount',
            name='parent',
        ),
        migrations.AddField(
            model_name='buyerdiscount',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_discounts', to='profiles.buyerprofile'),
        ),
        migrations.AddField(
            model_name='buyerdiscount',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_discounts', to='profiles.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='buyerdiscount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_products', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='buyerdiscount',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_variants', to='inventory.variant'),
        ),
        migrations.AlterField(
            model_name='productspecificbuyerdiscount',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.buyerprofile'),
        ),
    ]
