# Generated by Django 3.1 on 2020-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200822_1534'),
        ('inventory', '0012_auto_20200821_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='products', to='core.SubCategory'),
        ),
    ]
