# Generated by Django 3.1.12 on 2021-09-18 11:08

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocategoryrule',
            name='attribute_unit',
            field=django_mysql.models.EnumField(blank=True, choices=[('mg', 'Milligram'), ('gm', 'Gram'), ('kg', 'Kilogram'), ('lbs', 'lbs')], null=True),
        ),
    ]
