# Generated by Django 3.1.12 on 2022-01-13 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20220113_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerdiscount',
            old_name='discount',
            new_name='discount_value',
        ),
    ]
