# Generated by Django 3.1 on 2020-09-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20200822_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ('id',)},
        ),
    ]
