# Generated by Django 3.1.12 on 2021-09-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210918_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocategoryrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_category_rule', to='inventory.category'),
        ),
    ]
