# Generated by Django 3.1 on 2020-09-26 20:56

from django.db import migrations, models
import supplyr.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200917_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_lg',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.inventory.models.ProductImage.get_image_md_upload_path),
        ),
    ]
