# Generated by Django 3.1.12 on 2022-01-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220113_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSpecificBuyerDiscount',
        ),
    ]
