# Generated by Django 3.1.12 on 2021-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210918_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocategoryrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
