# Generated by Django 3.1.12 on 2022-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_delete_productspecificbuyerdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdiscount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
