# Generated by Django 3.1.2 on 2020-10-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productimage_image_lg'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
