# Generated by Django 3.1.12 on 2021-09-19 09:39

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210919_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='condition_type',
            field=django_mysql.models.EnumField(blank=True, choices=[('default', '----------------'), ('any', 'Any Rule Should Match'), ('all', 'All Rules Must Match')], null=True),
        ),
    ]
