# Generated by Django 3.2.4 on 2021-10-15 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('inventory', '0002_auto_20211015_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='awaiting_approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cancelled_by', django_mysql.models.EnumField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller'), ('staff', 'staff'), ('sales', 'sales')], null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyeraddress')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='profiles.buyerprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='profiles.salespersonprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_orders', to='profiles.sellerprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.variant')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyerprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='orders.order')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.salespersonprofile')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.sellerprofile')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
                'ordering': ('-created_at',),
            },
        ),
    ]
