# Generated by Django 3.1.2 on 2020-10-27 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20201019_2213'),
        ('core', '0012_auto_20201023_2330'),
        ('inventory', '0015_productimage_image_lg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='awaiting_approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', django_mysql.models.EnumField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller'), ('staff', 'staff')], null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyeraddress')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='core.buyerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_orders', to='core.sellerprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.variant')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
    ]
