# Generated by Django 3.1.12 on 2023-08-13 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0024_invoicetemplate_is_public'),
        ('inventory', '0017_auto_20220525_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='awaiting_approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cancelled_by', django_mysql.models.EnumField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller'), ('staff', 'staff'), ('sales', 'sales')], null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_extra_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=78, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyeraddress')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='profiles.buyerprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='profiles.salespersonprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_orders', to='profiles.sellerprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'unique_together': {('seller', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderStatusChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from=['name'], unique=True)),
                ('serial', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('serial',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_internal', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=['name'])),
                ('data_type', django_mysql.models.EnumField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number')], default='text')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_order_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstatuschoices')),
                ('sellers', models.ManyToManyField(related_name='order_status_variables', to='profiles.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', django_mysql.models.EnumField(choices=[('cheque', 'Cheque'), ('cash', 'Cash'), ('banktransfer', 'BankTransfer')], default='banktransfer')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.buyerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_variable_values', to='orders.order')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='values', to='orders.orderstatusvariable')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('extra_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('item_note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.variant')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyerprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='orders.order')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.salespersonprofile')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.sellerprofile')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', django_mysql.models.EnumField(choices=[('order_created', 'Order Created'), ('payment_added', 'Payment Added'), ('order_cancelled', 'Order Cancelled'), ('order_returned', 'Order Returned'), ('order_paid', 'Order Paid')], default='order_created')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='profiles.buyerprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.payment')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='profiles.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoice_pdfs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
