# Generated by Django 3.1.2 on 2020-10-27 21:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='awaiting_approval'),
        ),
    ]
