# Generated by Django 3.1.12 on 2023-08-13 11:59

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='items',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='awaiting_approval'),
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_index', models.CharField(max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='orders.order')),
            ],
            options={
                'unique_together': {('parent', 'group_index')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.ordergroup'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='order_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ordergroup'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='orders.ordergroup'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.ordergroup'),
        ),
        migrations.AddField(
            model_name='orderstatusvariablevalue',
            name='order_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_variable_values', to='orders.ordergroup'),
        ),
    ]
