# Generated by Django 3.1.2 on 2020-11-28 18:34

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_salesperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_by',
            field=django_mysql.models.EnumField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller'), ('staff', 'staff'), ('sales', 'sales')], null=True),
        ),
    ]
