# Generated by Django 3.2.4 on 2021-12-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_buyersellerconnection_generic_discount'),
        ('orders', '0002_orderitem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sellers', models.ManyToManyField(related_name='order_status_variables', to='profiles.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusVariableValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_variable_values', to='orders.order')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='values', to='orders.orderstatusvariable')),
            ],
        ),
    ]
