# Generated by Django 3.1.4 on 2020-12-26 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'Order Histories'},
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders_created', to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='history', to='orders.order'),
        ),
    ]
