# Generated by Django 3.2.4 on 2021-12-17 18:56

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatusvariable_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='awaiting_approval'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')]),
        ),
    ]
