# Generated by Django 3.1.12 on 2021-12-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211216_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_id',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
    ]
