# Generated by Django 3.1.4 on 2021-01-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201227_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Order Histories'},
        ),
    ]
