# Generated by Django 3.1.4 on 2021-02-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210109_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='sale_price',
            new_name='actual_price',
        ),
    ]
