# Generated by Django 3.2.4 on 2021-12-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211218_0026'),
        ('orders', '0007_auto_20211216_2023'),
    ]

    operations = [
    ]
