# Generated by Django 3.2.4 on 2021-12-18 07:19

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_0006_auto_20211218_0026_0007_auto_20211216_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusvariable',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=['name']),
        ),
    ]
