# Generated by Django 3.2.4 on 2021-12-20 09:22

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderstatusvariable_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusvariable',
            name='data_type',
            field=django_mysql.models.EnumField(choices=[('text', 'Text'), ('date', 'Date'), ('number', 'Number')], default='text'),
        ),
    ]
