# Generated by Django 3.1.12 on 2022-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
