# Generated by Django 3.1.12 on 2022-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220117_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_extra_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extra_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
