# Generated by Django 3.1.12 on 2022-02-05 09:22

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_buyersellerconnection_generic_discount'),
        ('orders', '0014_remove_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', django_mysql.models.EnumField(choices=[('cheque', 'Cheque'), ('cash', 'Cash'), ('banktransfer', 'BackTransfer')], default='banktransfer')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.buyerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.sellerprofile')),
            ],
        ),
    ]
