# Generated by Django 3.1.12 on 2022-02-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_buyersellerconnection_generic_discount'),
        ('orders', '0015_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='profiles.sellerprofile'),
        ),
    ]
