# Generated by Django 3.1.12 on 2022-02-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20220208_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.transaction'),
        ),
    ]
