# Generated by Django 3.1.12 on 2022-02-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20220208_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='ledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='orders.transaction'),
        ),
    ]
