# Generated by Django 3.1.12 on 2022-02-08 06:45

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220208_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ledger',
            name='transaction_type',
            field=django_mysql.models.EnumField(choices=[('order_created', 'Order Created'), ('payment_added', 'Payment Added'), ('order_cancelled', 'Order Cancelled')], default='order_created'),
        ),
    ]
