# Generated by Django 3.1.12 on 2022-02-16 06:42

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20220209_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=django_mysql.models.EnumField(choices=[('cheque', 'Cheque'), ('cash', 'Cash'), ('banktransfer', 'BankTransfer')], default='banktransfer'),
        ),
    ]
