# Generated by Django 3.1.12 on 2022-03-04 10:12

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderstatusvariable_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='awaiting_approval'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=django_mysql.models.EnumField(choices=[('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('returned', 'Returned')]),
        ),
    ]
