# Generated by Django 3.1.12 on 2022-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20220322_1355'),
        ('orders', '0026_auto_20220304_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('seller', 'order_number')},
        ),
    ]
