# Generated by Django 3.1.12 on 2022-03-22 08:26

from django.db import migrations
from django.shortcuts import get_object_or_404


class Migration(migrations.Migration):
    
    def custom_task(self,schema_editor):
        Order = self.get_model("orders","Order")
        SellerProfile = self.get_model("profiles","SellerProfile")
        orders = Order.objects.all().order_by("created_at")
        seller_orders = {order.seller.id:[] for order in orders}
        for order in orders:
            seller_orders[order.seller.id].append(order)
            
        for seller_id,orders in seller_orders.items():
            seller_profile = get_object_or_404(SellerProfile,id=seller_id)
            for order in orders:
                order.order_number = (seller_profile.order_number_counter + 1)
                order.save()
                seller_profile.order_number_counter += 1
                seller_profile.save()

    dependencies = [
        ('orders', '0027_auto_20220322_1355'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop)
    ]
