# Generated by Django 3.1.12 on 2022-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_number_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
