# Generated by Django 3.1.12 on 2022-08-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_manuallycreatedbuyer_created_by_seller'),
        ('orders', '0029_auto_20220322_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.buyeraddress'),
        ),
    ]
