# Generated by Django 3.1.12 on 2022-12-23 05:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20221101_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=django_mysql.models.EnumField(choices=[('order_created', 'Order Created'), ('payment_added', 'Payment Added'), ('order_cancelled', 'Order Cancelled'), ('order_paid', 'Order Paid')], default='order_created'),
        ),
    ]
