# Generated by Django 3.2.4 on 2023-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=78, null=True),
        ),
    ]
