# Generated by Django 3.0.8 on 2020-07-21 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('entity_category', models.IntegerField(choices=[(1, 'Manufacturer'), (2, 'Distributer'), (3, 'Wholeseller')])),
                ('entity_type', models.CharField(choices=[('pvtltd', 'Private Limited'), ('llp', 'Limited Liablity Partnership'), ('part', 'Partnership'), ('prop', 'Propertieship')], max_length=15)),
                ('is_gst_enrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
