# Generated by Django 3.0.8 on 2020-07-27 19:19

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entity_category',
            field=django_mysql.models.EnumField(blank=True, choices=[('M', 'Manufacturer'), ('D', 'Distributer'), ('W', 'Wholeseller')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entity_type',
            field=django_mysql.models.EnumField(blank=True, choices=[('pvtltd', 'Private Limited'), ('llp', 'Limited Liablity Partnership'), ('part', 'Partnership'), ('prop', 'Propertieship')], null=True),
        ),
    ]
