# Generated by Django 3.1.4 on 2021-01-08 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplyr.utils.otp


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVerificationOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=supplyr.utils.otp.generate_otp, max_length=10)),
                ('mobile_number', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_count', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
