# Generated by Django 3.0.8 on 2020-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='gst_certificate',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='uploads/gst_certificates'),
        ),
    ]
