# Generated by Django 3.1 on 2020-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200821_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category-images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='category-images/'),
        ),
    ]
