# Generated by Django 3.0.8 on 2020-07-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entity_gst_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Manufacturer'), (2, 'Distributer'), (3, 'Wholeseller')], null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('pvtltd', 'Private Limited'), ('llp', 'Limited Liablity Partnership'), ('part', 'Partnership'), ('prop', 'Propertieship')], max_length=15, null=True),
        ),
    ]
