# Generated by Django 3.1 on 2020-08-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200822_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
