# Generated by Django 3.0.8 on 2020-07-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200723_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entity',
            new_name='Profile',
        ),
    ]
