# Generated by Django 3.1 on 2020-08-25 14:43

from django.db import migrations, models
import supplyr.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.core.models.Category.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to=supplyr.core.models.Category.get_image_sm_upload_path),
        ),
    ]
