# Generated by Django 3.1 on 2020-09-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20200917_1912'),
        ('core', '0006_auto_20200825_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='SellerProfile',
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name_plural': 'Seller Profiles'},
        ),
    ]
