# Generated by Django 3.0.8 on 2020-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200724_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operational_fields',
            field=models.ManyToManyField(to='core.SubCategory'),
        ),
    ]
