# Generated by Django 3.1 on 2020-09-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200917_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
