# Generated by Django 3.1 on 2020-09-18 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200917_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BuyerProfile',
                'verbose_name_plural': 'BuyerProfiles',
            },
        ),
    ]
