# Generated by Django 3.1 on 2020-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_productimage_image_lg'),
        ('core', '0009_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='favourite_products',
            field=models.ManyToManyField(related_name='marked_favourite_by', to='inventory.Product'),
        ),
    ]
