# Generated by Django 3.0.8 on 2020-07-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200727_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['serial']},
        ),
    ]
