# Generated by Django 3.1.2 on 2020-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
