# Generated by Django 3.1.2 on 2020-11-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201104_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='connection_code',
            field=models.CharField(default='AA1234', max_length=15),
            preserve_default=False,
        ),
    ]
