# Generated by Django 3.1.2 on 2020-11-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import supplyr.profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('favourite_products', models.ManyToManyField(related_name='marked_favourite_by', to='inventory.Product')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BuyerProfile',
                'verbose_name_plural': 'BuyerProfiles',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_category', django_mysql.models.EnumField(blank=True, choices=[('M', 'Manufacturer'), ('D', 'Distributer'), ('W', 'Wholeseller')], null=True)),
                ('entity_type', django_mysql.models.EnumField(blank=True, choices=[('pvtltd', 'Private Limited'), ('llp', 'Limited Liablity Partnership'), ('part', 'Partnership'), ('prop', 'Propertieship')], null=True)),
                ('is_gst_enrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('tan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_certificate', models.FileField(blank=True, max_length=150, null=True, upload_to=supplyr.profiles.models.get_gst_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_code', models.CharField(max_length=15)),
                ('operational_fields', models.ManyToManyField(blank=True, to='inventory.SubCategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller Profiles',
            },
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', django_mysql.models.EnumField(choices=[('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('RJ', 'Rajasthan'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('TG', 'Telangana'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chattisgarh'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('MP', 'Madhya Pradesh'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('TR', 'Tripura'), ('UA', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry')])),
                ('phone', models.CharField(max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.buyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerSellerConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections', to='profiles.buyerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections', to='profiles.sellerprofile')),
            ],
            options={
                'verbose_name': 'BuyerSellerConnection',
                'verbose_name_plural': 'BuyerSellerConnections',
                'unique_together': {('seller', 'buyer', 'is_active', 'deactivated_at')},
            },
        ),
        migrations.AddConstraint(
            model_name='buyeraddress',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('owner',), name='unique_default_address'),
        ),
    ]
