# Generated by Django 3.1.2 on 2020-11-28 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_salespersonprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ManuallyCreatedBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.buyerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.salespersonprofile')),
            ],
        ),
    ]
