# Generated by Django 3.1.12 on 2021-12-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_buyersellerconnection_generic_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='prefix',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
