# Generated by Django 3.1.2 on 2020-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201104_1539'),
        ('profiles', '0003_buyersellerconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersellerconnection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='buyersellerconnection',
            unique_together={('seller', 'buyer', 'is_active')},
        ),
    ]
