# Generated by Django 3.1.2 on 2020-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuallycreatedbuyer',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
