# Generated by Django 3.1.12 on 2021-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_sellerprofile_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='prefix',
            new_name='invoice_prefix',
        ),
    ]
