# Generated by Django 3.1.2 on 2020-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201104_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersellerconnection',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
