# Generated by Django 3.1.4 on 2021-01-02 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_manuallycreatedbuyer_is_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespersonprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='salesperson_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SalespersonPreregisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('is_settled', models.BooleanField(default=False)),
                ('salesperson_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregistrations', to='profiles.salespersonprofile')),
            ],
        ),
    ]
