# Generated by Django 3.1.4 on 2021-01-17 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_auto_20201106_2010'),
        ('profiles', '0005_auto_20210103_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, related_name='marked_favourite_by', to='inventory.Product'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
