# Generated by Django 3.1.2 on 2020-11-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sellerprofile_connection_code'),
        ('profiles', '0005_buyersellerconnection_deactivated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buyersellerconnection',
            unique_together={('seller', 'buyer', 'is_active', 'deactivated_at')},
        ),
    ]
