# Generated by Django 3.1.12 on 2021-12-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211224_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='currency_representation',
            field=models.CharField(blank=True, default='₹', max_length=75, null=True),
        ),
    ]
