# Generated by Django 3.1.12 on 2021-06-25 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210117_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
