# Generated by Django 3.1.12 on 2022-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20211227_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='translation',
            field=models.JSONField(default={}),
        ),
    ]
