# Generated by Django 3.1.12 on 2021-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_sellerprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='documents'),
        ),
    ]
