# Generated by Django 3.1.12 on 2022-01-03 08:47

from django.db import migrations, models
import supplyr.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_sellerprofile_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='translation',
            field=models.JSONField(default=supplyr.profiles.models.translation_default),
        ),
    ]
