# Generated by Django 3.1.12 on 2021-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210625_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_approved',
        ),
    ]
