# Generated by Django 3.1.12 on 2022-01-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220103_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='translation',
            new_name='translations',
        ),
    ]
