# Generated by Django 3.1.12 on 2021-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_sellerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
