# Generated by Django 3.1.12 on 2022-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20220104_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersellerconnection',
            name='generic_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
