# Generated by Django 3.1.12 on 2021-06-28 16:20

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_sellerprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=django_mysql.models.EnumField(blank=True, choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_more_info', 'Need More Information'), ('permanently_rejected', 'Permanently Rejected')], null=True),
        ),
    ]
