# Generated by Django 3.2.4 on 2022-02-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_buyersellerconnection_generic_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyeraddress',
            old_name='state',
            new_name='state_old',
        ),
    ]
