# Generated by Django 3.1.12 on 2021-06-30 08:57

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210628_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='status',
            field=django_mysql.models.EnumField(blank=True, choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_more_info', 'Need More Information'), ('permanently_rejected', 'Permanently Rejected'), ('new', 'New')], null=True),
        ),
    ]
