# Generated by Django 3.1.12 on 2021-07-02 10:34

from django.db import migrations, models
import supplyr.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210630_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=supplyr.profiles.models.get_gst_upload_path),
        ),
    ]
