# Generated by Django 3.2.4 on 2022-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_sellerprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeraddress',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
