# Generated by Django 3.1.12 on 2022-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_buyeraddress_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='order_number_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='order_number_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
