# Generated by Django 3.1.12 on 2021-08-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210805_1348'),
        ('profiles', '0017_auto_20210704_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='operational_fields',
            field=models.ManyToManyField(blank=True, to='inventory.Category'),
        ),
    ]
