# Generated by Django 3.1.12 on 2021-10-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210805_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeraddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_address', to='profiles.buyerprofile'),
        ),
    ]
