# Generated by Django 3.1.12 on 2022-09-02 19:54

from django.db import migrations, models
import supplyr.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_manuallycreatedbuyer_created_by_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='translations',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user_settings',
            field=models.JSONField(default=supplyr.profiles.models.user_setting_config),
        ),
    ]
