# Generated by Django 3.1.12 on 2022-10-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20220928_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='default_gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_gst_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
