# Generated by Django 3.1.12 on 2022-11-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20220525_0206'),
        ('profiles', '0021_auto_20221006_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='product_price_includes_taxes',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_addresses', to='profiles.sellerprofile')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='profiles.addressstate')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOverrideGst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_categories', to='profiles.sellerprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='selleraddress',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('owner',), name='unique_seller_address'),
        ),
    ]
