# Generated by Django 3.1.12 on 2023-08-17 15:56

from django.db import migrations, models
import supplyr.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_invoicetemplate_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='currency_representation',
            field=models.CharField(blank=True, default='₹{{amount}}', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user_settings',
            field=models.JSONField(blank=True, default=supplyr.profiles.models.user_setting_config, null=True),
        ),
    ]
