# Generated by Django 3.1.12 on 2021-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210626_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofilereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
