# Generated by Django 3.1.12 on 2021-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sellerprofilereview_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
