# Generated by Django 3.1.12 on 2021-06-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210628_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofilereview',
            name='updated_at',
        ),
    ]
