# Generated by Django 3.1.12 on 2021-06-28 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_sellerprofilereview_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 12, 25, 21, 708070)),
        ),
    ]
