# Generated by Django 3.1.12 on 2021-06-28 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210628_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 21, 29, 23, 379224)),
        ),
    ]
