# Generated by Django 3.1.12 on 2021-06-28 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210628_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 21, 31, 16, 755891)),
        ),
    ]
