# Generated by Django 3.1.12 on 2021-06-28 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210628_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 22, 32, 54, 340449)),
        ),
    ]
