# Generated by Django 3.1.12 on 2021-06-30 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210630_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 14, 42, 3, 983105)),
        ),
    ]
