# Generated by Django 3.1.12 on 2021-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
