# Generated by Django 3.1.12 on 2021-07-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0014_auto_20210702_1604'),
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfileReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', django_mysql.models.EnumField(blank=True, choices=[('pending_approval', 'pending_approval'), ('approved', 'approved'), ('rejected', 'rejected'), ('need_more_info', 'need_more_info'), ('permanently_rejected', 'permanently_rejected'), ('new', 'new')], default='new', null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.sellerprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
