# Generated by Django 3.1.12 on 2021-07-04 15:48

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20210702_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='status',
            field=django_mysql.models.EnumField(blank=True, choices=[('pending_approval', 'pending_approval'), ('approved', 'approved'), ('rejected', 'rejected'), ('need_more_info', 'need_more_info'), ('permanently_rejected', 'permanently_rejected'), ('categories_selected', 'categories_selected'), ('new', 'new')], default='new', null=True),
        ),
    ]
