# Generated by Django 3.1.12 on 2021-07-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210704_2118'),
        ('reviewer', '0003_auto_20210704_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofilereview',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile_review', to='profiles.sellerprofile'),
        ),
    ]
